name: .NET CI

on:
  push:
    branches:
      - main

jobs:
  dev:
    name: Dev Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python dev.py

  test:
    name: Test Job
    runs-on: ubuntu-latest
    needs: dev
    steps:
      - uses: actions/checkout@v4
      - run: python test.py

  prod:
    name: Prod Job
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - run: python prod.py
